/**
 * i18n setup — French primary, Arabic and English secondary (T-388).
 *
 * Strings are kept inline (no JSON files) so the type checker verifies
 * every key exists at compile time. Translations are flat dotted keys
 * for predictable lookup.
 *
 * T-388: the `en` locale is a first-class citizen now, and every locale is
 * the deep merge of its HAND-MAINTAINED base dictionary (fr/ar/en.ts — the
 * curated keys) with its GENERATED dictionary (gen/fr|ar|en.ts — the ~2.8k
 * keys the codemod assigned to formerly hardcoded strings; regenerated by
 * scripts/i18n/apply-i18n.mjs dict, never edited by hand).
 */
import i18next from "i18next";
import { initReactI18next } from "react-i18next";
import { fr } from "./fr";
import { ar } from "./ar";
import { en } from "./en";
import { genFr } from "./gen/fr";
import { genAr } from "./gen/ar";
import { genEn } from "./gen/en";

type Dict = { [key: string]: string | Dict };

function deepMerge(base: Dict, extra: Dict): Dict {
  const out: Dict = { ...base };
  for (const [k, v] of Object.entries(extra)) {
    const b = out[k];
    out[k] =
      typeof b === "object" && b !== null && typeof v === "object" && v !== null
        ? deepMerge(b as Dict, v as Dict)
        : v;
  }
  return out;
}

void i18next.use(initReactI18next).init({
  resources: {
    fr: { translation: deepMerge(fr as unknown as Dict, genFr as unknown as Dict) },
    ar: { translation: deepMerge(ar as unknown as Dict, genAr as unknown as Dict) },
    en: { translation: deepMerge(en as unknown as Dict, genEn as unknown as Dict) },
  },
  lng: "fr",
  fallbackLng: "fr",
  supportedLngs: ["fr", "ar", "en"],
  interpolation: { escapeValue: false },
  returnNull: false,
});

export default i18next;
