/**
 * particle-import-engine — Image Loader
 *
 * Loads images from three sources: local file path, HTTP(S) URL, or raw Buffer.
 * Uses the `sharp` library for server-side image decoding (no DOM required).
 * Returns a normalised RGBA pixel buffer with dimensions.
 */

import { readFileSync } from 'fs';
import { basename } from 'path';
import * as http from 'http';
import * as https from 'https';
import sharp from 'sharp';
import { ImageSource } from '../types';
import { ImageLoadError } from '../errors';

/** Result of a successful image load. */
export interface LoadedImage {
  /** Raw RGBA pixel data (4 bytes per pixel). */
  data: Buffer;
  /** Image width in pixels. */
  width: number;
  /** Image height in pixels. */
  height: number;
  /** Number of channels (always 4 — RGBA). */
  channels: 4;
  /** Human-readable source label for logging. */
  sourceLabel: string;
}

/**
 * Load an image from any supported source and return raw RGBA pixel data.
 *
 * @param source - Image source specification.
 * @param maxDim - Maximum dimension for initial downscale (default 180).
 *                 This keeps memory usage reasonable for large images.
 */
export async function loadImage(source: ImageSource, maxDim = 180): Promise<LoadedImage> {
  try {
    let rawBuffer: Buffer;
    let label: string;

    if (source.filePath) {
      label = basename(source.filePath);
      rawBuffer = readFileSync(source.filePath);
    } else if (source.url) {
      label = source.url;
      rawBuffer = await fetchBuffer(source.url);
    } else if (source.buffer) {
      label = '<Buffer>';
      rawBuffer = source.buffer;
    } else if (source.fallback) {
      // Fallback pattern is handled by the fallback generator, not here.
      throw new ImageLoadError(
        'Fallback pattern must be generated by the FallbackGenerator, not the loader.',
      );
    } else {
      throw new ImageLoadError('No valid image source provided. Supply filePath, url, buffer, or fallback.');
    }

    // Decode with sharp — ensure RGBA output, downscale to maxDim.
    const pipeline = sharp(rawBuffer).raw().ensureAlpha();

    // Get metadata first to decide on downscale.
    const metadata = await pipeline.metadata();
    const origW = metadata.width ?? 1;
    const origH = metadata.height ?? 1;

    let targetW = origW;
    let targetH = origH;

    if (origW > maxDim || origH > maxDim) {
      if (origW >= origH) {
        targetW = maxDim;
        targetH = Math.round(origH * (maxDim / origW));
      } else {
        targetH = maxDim;
        targetW = Math.round(origW * (maxDim / origH));
      }
    }

    // Resize and get raw RGBA bytes.
    const { data, info } = await pipeline
      .resize(targetW, targetH, { fit: 'fill' })
      .toBuffer({ resolveWithObject: true });

    return {
      data: data as Buffer,
      width: info.width,
      height: info.height,
      channels: 4,
      sourceLabel: label,
    };
  } catch (err) {
    if (err instanceof ImageLoadError) throw err;
    throw new ImageLoadError(
      `Failed to load image: ${(err as Error).message}`,
      err as Error,
    );
  }
}

/**
 * Fetch a buffer from an HTTP(S) URL.
 */
function fetchBuffer(url: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, { timeout: 15_000 }, (res) => {
      if (res.statusCode && res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        // Follow redirect.
        fetchBuffer(res.headers.location).then(resolve).catch(reject);
        return;
      }
      if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
        reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        return;
      }
      const chunks: Buffer[] = [];
      res.on('data', (chunk: Buffer) => chunks.push(chunk));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', reject);
    }).on('error', reject)
      .on('timeout', function (this: http.ClientRequest) {
        this.destroy();
        reject(new Error(`Request timeout for ${url}`));
      });
  });
}
