/**
 * ExcelImportModal — 5-step desktop-only bulk import pipeline (plan §14).
 *
 *   1. Select .xlsx file
 *   2. Engine-driven parse + validate (dry-run preview)
 *   3. Review stats + errors + per-sheet detail
 *   4. Atomic bulk insert — single transaction wraps all sheets
 *   5. Download JSON + Excel reports
 *
 * Iteration 11: NOW USES the integrated `ImportEngine` (ported from the
 * standalone `excel-import-engine` package). The new engine brings:
 *   - Multi-schema support (ETAT clients + BON receipts + Devis + REF tables).
 *   - Idempotent upsert (re-importing the same file skips unchanged records).
 *   - Per-run audit trail (run ID, file checksum, errors, warnings, status).
 *   - JSON + Excel report generation for human review.
 *   - Robust validation: French-locale numbers, Algerian phone regex,
 *     monthlyArray aggregation, `#REF!` formula tolerance.
 *
 * Audit integration: every run emits `import.run_started` and
 * `import.run_completed` audit actions via `repos.audit.log()` — the
 * audit log becomes the canonical system of record for import activity.
 *
 * Built on UnifiedModal so the visual language matches every other modal
 * in the application.
 */
import { useRef, useState } from "react";
import {
  Upload, FileSpreadsheet, CheckCircle2, AlertTriangle,
  Loader2, FileUp, X, Download, FileJson, FileText,
} from "lucide-react";
import { useRepositories } from "../../app/providers/repository-provider";
import { useToast } from "../../app/providers/toast-provider";
import { useAuth } from "../../app/providers/auth-provider";
import { useSyncActions } from "../../app/providers/sync-provider";
import { UnifiedModal, type UnifiedModalProps } from "../../shared/ui/unified-modal";
import { Button } from "../../shared/ui/button";
import { Badge } from "../../shared/ui/badge";
import { ImportEngine } from "../../infrastructure/excel/import-engine";
import { RepositoryStorageAdapter } from "../../infrastructure/excel/import-engine/storage/repository-adapter";
import type { ImportContext } from "../../infrastructure/excel/import-engine";
import { downloadBlob } from "../../infrastructure/excel/export-engine";

/**
 * Trigger a browser download for an in-memory report. The bytes were
 * generated by the import engine and stashed in component state — the
 * download only fires when the user clicks a "Download" button.
 */
function downloadReport(
  report: { fileName: string; bytes: Uint8Array },
  mime: string,
): void {
  downloadBlob(report.bytes, report.fileName, mime);
}

type Stage = "select" | "preview" | "committing" | "done";
type Alert = NonNullable<UnifiedModalProps["alert"]>;

export function ExcelImportModal({
  open,
  onOpenChange,
  onImported,
}: {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  onImported?: (insertedCount: number) => void;
}) {
  const repos = useRepositories();
  const toast = useToast();
  const { session } = useAuth();
  const sync = useSyncActions();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const engineRef = useRef<ImportEngine | null>(null);

  const [stage, setStage] = useState<Stage>("select");
  const [fileName, setFileName] = useState<string | null>(null);
  // Keep the File object in component state so the commit() step can re-read
  // the bytes without relying on the <input type="file"> ref. The ref is
  // unreliable across React re-renders: when the modal transitions from the
  // "select" stage to the "preview" stage, the input element is unmounted,
  // which empties `fileInputRef.current.files` and causes the
  // "Fichier introuvable" error reported in production.
  const [fileBytes, setFileBytes] = useState<Uint8Array | null>(null);
  const [previewCtx, setPreviewCtx] = useState<ImportContext | null>(null);
  const [parsing, setParsing] = useState(false);
  const [commitCtx, setCommitCtx] = useState<ImportContext | null>(null);
  const [reports, setReports] = useState<{
    json?: { fileName: string; bytes: Uint8Array };
    excel?: { fileName: string; bytes: Uint8Array };
  } | null>(null);
  const [alert, setAlert] = useState<Alert | null>(null);
  /** Per-row errors collected during the commit (parent/student creation failures). */
  const [skipErrors, setSkipErrors] = useState<Array<{ rowIndex: number; identity: string; error: string }>>([]);

  function reset() {
    setStage("select");
    setFileName(null);
    setFileBytes(null);
    setPreviewCtx(null);
    setCommitCtx(null);
    setReports(null);
    setAlert(null);
    setSkipErrors([]);
    // Clear the underlying input so re-opening the modal lets the user pick
    // the same file again (the input's `change` event won't fire otherwise).
    if (fileInputRef.current) fileInputRef.current.value = "";
  }

  /** Build (or reuse) an ImportEngine wired to the project's audit log + real repositories. */
  function getEngine(): ImportEngine {
    if (!engineRef.current) {
      // The bridge adapter delegates ETAT upserts to ParentRepository +
      // StudentRepository — this is the fix that makes Excel imports
      // actually persist students into the CRM. Iteration 21 also wires
      // the LedgerRepository so each row's financial data (DEVIS ANNUEL,
      // DETTES, REMISE, REMBOURSEMENT, REGLEMENTS DETTES) is written as
      // ledger entries linked to the imported student.
      const storage = new RepositoryStorageAdapter({
        parents: repos.parents,
        students: repos.students,
        ledger: repos.ledger,
        tenantId: session?.tenantId ?? "default",
        actorId: session?.userId ?? "system",
        actorName: session?.displayName ?? "System",
      });
      engineRef.current = new ImportEngine({
        storage,
        auditSink: {
          async logAction(action, entityType, entityId, diff, note) {
            await repos.audit.log({
              action,
              entityType,
              entityId,
              actorId: session?.userId ?? "system",
              actorName: session?.displayName ?? "System",
              tenantId: session?.tenantId ?? "default",
              diff: diff ? { after: diff } : null,
              note: note ?? null,
            });
          },
        },
      });
    }
    return engineRef.current;
  }

  async function handleFile(file: File) {
    setParsing(true);
    setAlert(null);
    try {
      // Read the bytes ONCE here and stash them in component state so the
      // commit() step can re-use them without depending on the file input.
      // The File object itself is also fine to keep, but Uint8Array is
      // plain serializable memory that survives any React re-render.
      const buf = new Uint8Array(await file.arrayBuffer());
      setFileBytes(buf);
      setFileName(file.name);

      const engine = getEngine();
      // Dry-run import — validates + shows stats without writing to storage.
      const ctx = await engine.importFile(buf, file.name, {
        dryRun: true,
        source: { user: session?.email ?? "unknown" },
      });
      setPreviewCtx(ctx);
      setStage("preview");

      if (ctx.stats.rowsRead === 0) {
        setAlert({
          tone: "warning",
          title: "Aucune ligne à importer",
          description: "Le fichier est vide ou aucune feuille ne correspond à un schéma connu.",
        });
      } else if (ctx.stats.warnings > 0) {
        setAlert({
          tone: "info",
          title: `${ctx.stats.rowsRead} ligne(s) prête(s) à importer (${ctx.stats.warnings} avertissement(s))`,
          description: "Toutes les lignes seront importées. Les avertissements indiquent des données manquantes ou non standard qui ont été corrigées automatiquement (ex: CLASSE manquant → « Non assignée »).",
        });
      } else {
        setAlert({
          tone: "info",
          title: `${ctx.stats.rowsRead} ligne(s) prête(s) à importer`,
          description: "Vérifiez l'aperçu puis cliquez sur 'Importer atomiquement'.",
        });
      }
    } catch (e) {
      setAlert({
        tone: "error",
        title: "Échec de la lecture",
        description: e instanceof Error ? e.message : String(e),
      });
    } finally {
      setParsing(false);
    }
  }

  async function commit() {
    if (!previewCtx || !session) return;
    if (!fileBytes || !fileName) {
      // Should never happen — handleFile() populates both before enabling
      // commit — but guard anyway so the user sees a clear message instead
      // of a generic crash.
      setStage("preview");
      setAlert({
        tone: "error",
        title: "Fichier introuvable",
        description:
          "Le fichier source n'est plus en mémoire. Veuillez fermer cette fenêtre, rouvrir l'import et recharger le fichier .xlsx.",
      });
      return;
    }
    setStage("committing");
    setAlert(null);
    try {
      const engine = getEngine();
      const ctx = await engine.importFile(fileBytes, fileName, {
        dryRun: false,
        source: { user: session?.email ?? "unknown" },
      });

      // Iteration 14 + 0027 unification — enqueue sync entries for every
      // successfully imported row.
      //
      // When Supabase IS configured, the SupabaseParentRepository /
      // SupabaseStudentRepository / SupabaseLedgerRepository that the
      // importer invoked have ALREADY written to Supabase via the
      // idempotent `upsert_*_from_import` RPCs (migration 0027). The
      // queue entries below are an audit trail + a safety net for the
      // offline case (when Supabase isn't configured, the importer
      // writes to the mock layer and the queue is drained later).
      //
      // PAYLOAD-SHAPE FIX: Previously the modal enqueued the whole
      // `StorageRecord` wrapper as `payload`, but `defaultPushHandler`
      // reads fields like `firstName`, `lastName`, `displayName`,
      // `parentId`, `amount` directly off `payload`. Those fields live
      // on the domain entities (Parent / Student / LedgerEntry), NOT
      // on the StorageRecord wrapper or the raw ImportRecord. The fix:
      // iterate the `entities` array on each StorageRecord and enqueue
      // ONE sync entry per domain entity, using the entity object itself
      // as the payload. This way the RPC receives the correct shape and
      // Supabase actually gets the data.
      //
      // BATCHED ENQUEUE: Previously the modal called `sync.enqueue()` in
      // a loop — once per domain entity (parent + student + ledger_entry
      // per row × ~390 rows ≈ 1,170 entries). Each call emitted a
      // snapshot, triggering 1,170 React re-renders across every
      // `useSyncStatus()` consumer (topbar indicator, sync tab, etc.).
      // The user saw "1,170 sync notifications during sync" — even
      // though only the final count mattered. Batching collapses all
      // of that to ONE IndexedDB transaction + ONE snapshot emission.
      //
      // The `operation` field is informational — the upsert RPCs handle
      // insert-vs-update idempotently at the database layer.
      const storageForSync = engine.getStorage();
      const allRecords = typeof storageForSync.listInsertedForRun === "function"
        ? await storageForSync.listInsertedForRun(ctx.runId)
        : [];
      // Build the full enqueue payload list in one pass — no per-entry
      // await, no per-entry snapshot emission.
      const batchInputs: Array<{
        entity: "parent" | "student" | "ledger_entry" | "payment";
        operation: "insert";
        payload: Record<string, unknown>;
        isMock: false;
        sourceFile: string;
        importRunId: string;
      }> = [];
      for (const rec of allRecords) {
        // Each StorageRecord may carry 0..N resolved domain entities
        // (parent, student, ledger_entry). Enqueue one sync entry per
        // entity so the dispatcher routes to the correct upsert RPC.
        const entities = rec.entities ?? [];
        if (entities.length === 0) {
          // Non-ETAT row (BON, Devis, REF) — no domain entity to sync.
          continue;
        }
        for (const { kind, entity } of entities) {
          // Payload is the domain entity itself — `defaultPushHandler`
          // reads firstName/lastName/displayName/parentId/amount/etc.
          // directly off this object.
          batchInputs.push({
            entity: kind as "parent" | "student" | "ledger_entry" | "payment",
            operation: "insert",
            payload: entity as unknown as Record<string, unknown>,
            // Excel import = real data → isMock: false. The sync layer
            // will push this to Supabase as soon as the desktop is online.
            isMock: false,
            sourceFile: fileName,
            importRunId: ctx.runId,
          });
        }
      }
      // ONE batched enqueue → ONE snapshot emission → ONE drain schedule.
      // This replaces the previous per-entity loop that caused ~1,170
      // snapshot emissions during a single Excel commit.
      await sync.enqueueBatch(batchInputs);
      const enqueuedForSync = batchInputs.length;

      // Capture report bytes from the engine. The engine generates the
      // bytes in-memory and does NOT auto-download them — the user must
      // click a "Download" button below. This fixes the "every Excel
      // upload generates another Excel + JSON file at the beginning and
      // at the end" bug where files were auto-downloaded on every commit.
      setReports(ctx.reports ?? null);
      setCommitCtx(ctx);
      setStage("done");

      const inserted = ctx.stats.rowsImported;
      const updated = ctx.stats.rowsUpdated;
      const skipped = ctx.stats.rowsSkipped;

      // Collect the per-row errors from the storage adapter so we can show
      // the user WHY rows were skipped (instead of the previous opaque
      // "X ignoré(s)" message). The adapter logs every parent/student
      // creation failure with the actual RPC error message.
      const storage = engine.getStorage();
      const skipErrors = storage instanceof RepositoryStorageAdapter
        ? storage.getErrorsForRun(ctx.runId)
        : [];
      if (skipErrors.length > 0) {
        setSkipErrors(skipErrors);
      }

      if (skipped > 0 && skipErrors.length > 0) {
        // Show a WARNING (not success) because rows were silently dropped.
        const firstErr = skipErrors[0];
        toast.showWarning(
          "Import partiel — lignes ignorées",
          `${inserted} inséré(s), ${updated} mis à jour, ${skipped} ignoré(s). ` +
          `Première erreur (ligne ${firstErr.rowIndex}, "${firstErr.identity}"): ${firstErr.error}. ` +
          `Voir la liste complète ci-dessous et la console (Ctrl+Shift+I).`,
        );
      } else {
        toast.showSuccess(
          "Import atomique réussi",
          `${inserted} inséré(s), ${updated} mis à jour, ${skipped} ignoré(s) en ${ctx.durationMs ?? 0} ms. ${enqueuedForSync} enregistrement(s) en file d'attente de synchronisation.`,
        );
      }
      onImported?.(inserted);

      // Trigger immediate sync push so Supabase gets the data now rather
      // than waiting for the next periodic sync cycle.
      try {
        await sync.syncNow();
      } catch (syncErr) {
        console.warn("[ExcelImportModal] sync.syncNow() failed — data is queued and will sync later:", syncErr);
      }
    } catch (e) {
      setStage("preview");
      setAlert({
        tone: "error",
        title: "Échec de l'import atomique",
        description: e instanceof Error ? e.message : String(e),
      });
    }
  }

  const showFooter = stage === "preview" || stage === "done";
  const totalRows = previewCtx?.stats.rowsRead ?? 0;
  const totalErrors = previewCtx?.errors.length ?? 0;
  const totalWarnings = previewCtx?.stats.warnings ?? 0;
  // Iteration 21: "Import student no matter what" — allow commit even with
  // validation errors. Errors are now downgraded to warnings by the validator,
  // so `totalErrors` should always be 0. But even if some slip through, we
  // only block commit when there are zero rows to import.
  const canCommit = totalRows > 0;

  return (
    <UnifiedModal
      open={open}
      onOpenChange={(o) => {
        if (!o && stage === "committing") return; // don't close while committing
        onOpenChange(o);
        if (!o) setTimeout(reset, 200);
      }}
      size="lg"
      variant="dialog"
      icon={FileSpreadsheet}
      iconTone="primary"
      title="Import Excel — Suivis clients"
      description="Pipeline 5 étapes: sélection → parse → mapping → validation → insertion atomique. Moteur intégré avec audit log + rapports JSON/Excel."
      alert={alert}
      onDismissAlert={() => setAlert(null)}
      footer={
        showFooter ? (
          <>
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              {stage === "done" ? "Fermer" : "Annuler"}
            </Button>
            {stage === "preview" && (
              <Button onClick={commit} disabled={!canCommit}>
                <FileUp className="h-4 w-4" /> Importer atomiquement ({totalRows})
              </Button>
            )}
            {stage === "done" && (
              <Button onClick={() => onOpenChange(false)}>
                <CheckCircle2 className="h-4 w-4" /> Terminé
              </Button>
            )}
          </>
        ) : null
      }
    >
      {/* Stage: select file */}
      {stage === "select" && (
        <div className="space-y-4">
          <label
            className="flex flex-col items-center justify-center gap-3 rounded-lg border-2 border-dashed border-border p-8 cursor-pointer hover:bg-accent/5 transition-colors"
            onDragOver={(e) => e.preventDefault()}
            onDrop={(e) => {
              e.preventDefault();
              const f = e.dataTransfer.files?.[0];
              if (f) void handleFile(f);
            }}
          >
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary">
              {parsing ? <Loader2 className="h-6 w-6 animate-spin" /> : <Upload className="h-6 w-6" />}
            </div>
            <div className="text-center">
              <p className="text-sm font-medium">
                {parsing ? "Lecture du fichier…" : "Cliquez ou déposez un fichier .xlsx"}
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                Format attendu : Suivis clients — feuilles ETAT / BON / Devis / REF.
              </p>
            </div>
            <input
              ref={fileInputRef}
              type="file"
              accept=".xlsx,.xlsm"
              className="hidden"
              onChange={(e) => {
                const f = e.target.files?.[0];
                if (f) void handleFile(f);
              }}
            />
          </label>
          <div className="rounded-md bg-muted/30 p-3 text-xs text-muted-foreground">
            <p className="font-medium text-foreground mb-1">Règles d'import (plan §14 + moteur intégré):</p>
            <ul className="space-y-0.5 list-disc list-inside">
              <li>4 schémas supportés : ETAT (clients), BON (reçus), Devis, REF (références).</li>
              <li>Identité : NEM + NOM pour ETAT ; eleve + client pour BON ; etc.</li>
              <li>Idempotent : ré-importer le même fichier ne crée pas de doublons (checksum SHA-256).</li>
              <li>Tolérant aux #REF! dans les montants (warning, pas erreur).</li>
              <li>Numéros de téléphone algériens (06/07 +213).</li>
              <li>Tableau mensuel REGLEMENTS DETTES agrégé en 12 colonnes sep..aug.</li>
              <li>Audit log : chaque run émet import.run_started + import.run_completed.</li>
              <li>Rapports JSON + Excel générés automatiquement après l'import.</li>
            </ul>
          </div>
        </div>
      )}

      {/* Stage: preview */}
      {stage === "preview" && previewCtx && (
        <div className="space-y-4">
          <div className="flex items-center justify-between rounded-md border border-border p-3">
            <div className="flex items-center gap-2">
              <FileSpreadsheet className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium">{fileName}</span>
            </div>
            <div className="flex items-center gap-2">
              <Badge variant={canCommit ? "default" : "destructive"}>
                {previewCtx.stats.rowsRead} ligne(s)
              </Badge>
              {totalErrors > 0 && (
                <Badge variant="destructive">{totalErrors} erreur(s)</Badge>
              )}
              {previewCtx.stats.warnings > 0 && (
                <Badge variant="secondary">{previewCtx.stats.warnings} warning(s)</Badge>
              )}
              <Button size="sm" variant="ghost" onClick={() => fileInputRef.current?.click()}>
                <X className="h-3 w-3" /> Changer
              </Button>
            </div>
          </div>

          {/* Per-sheet stats */}
          {previewCtx.sheetResults.length > 0 && (
            <div className="rounded-md border border-border overflow-hidden">
              <table className="w-full text-xs">
                <thead className="bg-muted/30 text-muted-foreground">
                  <tr>
                    <th className="text-left p-2">Feuille</th>
                    <th className="text-left p-2">Schéma</th>
                    <th className="text-right p-2">Lues</th>
                    <th className="text-right p-2">Insérées</th>
                    <th className="text-right p-2">Mises à jour</th>
                    <th className="text-right p-2">Ignorées</th>
                    <th className="text-right p-2">Rejetées</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {previewCtx.sheetResults.map((s, i) => (
                    <tr key={i}>
                      <td className="p-2 font-medium">{s.sheet}</td>
                      <td className="p-2 uppercase text-muted-foreground">{s.schema}</td>
                      <td className="p-2 text-right font-mono">{s.rowsRead}</td>
                      <td className="p-2 text-right font-mono text-status-success">{s.rowsImported}</td>
                      <td className="p-2 text-right font-mono text-status-info">{s.rowsUpdated}</td>
                      <td className="p-2 text-right font-mono text-muted-foreground">{s.rowsSkipped}</td>
                      <td className="p-2 text-right font-mono text-status-danger">{s.rowsRejected}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Error list */}
          {previewCtx.errors.length > 0 && (
            <div className="rounded-md border border-status-danger/30 bg-status-danger/5 p-3 max-h-32 overflow-y-auto">
              <p className="text-xs font-medium text-status-danger mb-1">
                Erreurs de validation ({previewCtx.errors.length}) :
              </p>
              <ul className="space-y-0.5 text-xs">
                {previewCtx.errors.slice(0, 20).map((e, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="font-mono text-status-danger shrink-0">
                      {e.sheet ?? "?"}/L{e.rowIndex ?? "?"}/{e.rule}:
                    </span>
                    <span className="text-muted-foreground">{e.message}</span>
                  </li>
                ))}
                {previewCtx.errors.length > 20 && (
                  <li className="text-muted-foreground italic">
                    + {previewCtx.errors.length - 20} autre(s) erreur(s)…
                  </li>
                )}
              </ul>
            </div>
          )}

          {/* Run metadata */}
          <div className="rounded-md bg-muted/30 p-3 text-xs text-muted-foreground">
            <p className="font-medium text-foreground mb-1">Métadonnées du run :</p>
            <div className="grid grid-cols-2 gap-x-4 gap-y-0.5 font-mono">
              <span>Run ID :</span><span className="text-foreground">{previewCtx.runId}</span>
              <span>Checksum :</span><span className="text-foreground truncate">{previewCtx.fileChecksum?.slice(0, 24)}…</span>
              <span>Taille :</span><span className="text-foreground">{previewCtx.fileSize} octets</span>
              <span>Durée :</span><span className="text-foreground">{previewCtx.durationMs ?? 0} ms</span>
            </div>
          </div>
        </div>
      )}

      {/* Stage: committing */}
      {stage === "committing" && (
        <div className="flex flex-col items-center justify-center gap-3 py-8">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p className="text-sm font-medium">Insertion atomique en cours…</p>
          <p className="text-xs text-muted-foreground">BEGIN…COMMIT — tout réussit ou tout échoue. Rapports générés après commit.</p>
        </div>
      )}

      {/* Stage: done */}
      {stage === "done" && commitCtx && (
        <div className="space-y-4">
          <div className={`rounded-md border p-4 text-center ${skipErrors.length > 0 ? "border-status-warning/40 bg-status-warning/5" : "border-status-success/40 bg-status-success/5"}`}>
            {skipErrors.length > 0 ? (
              <AlertTriangle className="h-10 w-10 text-status-warning mx-auto mb-2" />
            ) : (
              <CheckCircle2 className="h-10 w-10 text-status-success mx-auto mb-2" />
            )}
            <p className={`text-base font-medium ${skipErrors.length > 0 ? "text-status-warning" : "text-status-success"}`}>
              {skipErrors.length > 0 ? "Import partiel" : "Import réussi"}
            </p>
            <p className="text-sm text-muted-foreground mt-1">
              {commitCtx.stats.rowsImported} inséré(s), {commitCtx.stats.rowsUpdated} mis à jour, {commitCtx.stats.rowsSkipped} ignoré(s) en {commitCtx.durationMs ?? 0} ms.
            </p>
          </div>

          {/* Skip errors — the actual reason rows were dropped */}
          {skipErrors.length > 0 && (
            <div className="rounded-md border border-status-danger/30 bg-status-danger/5 p-3 max-h-48 overflow-y-auto">
              <p className="text-xs font-medium text-status-danger mb-1">
                {skipErrors.length} ligne(s) ignorée(s) à cause d'erreurs (affichage des 20 premières) :
              </p>
              <ul className="space-y-0.5 text-xs">
                {skipErrors.slice(0, 20).map((e, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="font-mono text-status-danger shrink-0">
                      L{e.rowIndex} ({e.identity}):
                    </span>
                    <span className="text-muted-foreground break-all">
                      {typeof e.error === "object" ? JSON.stringify(e.error) : String(e.error)}
                    </span>
                  </li>
                ))}
                {skipErrors.length > 20 && (
                  <li className="text-muted-foreground italic">
                    + {skipErrors.length - 20} autre(s) erreur(s)… (voir la console avec Ctrl+Shift+I)
                  </li>
                )}
              </ul>
              <div className="mt-2 pt-2 border-t border-status-danger/20 text-[11px] text-muted-foreground">
                <p className="font-medium text-foreground mb-0.5">Causes possibles :</p>
                <ul className="list-disc list-inside space-y-0.5">
                  <li>La migration <code className="font-mono">0028_shared_schema_extensions.sql</code> n'est pas appliquée sur Supabase → les paramètres <code className="font-mono">p_transport_destination</code> / <code className="font-mono">p_grade_level_code</code> sont rejetés.</li>
                  <li>Le <code className="font-mono">tenant_id</code> de la session n'existe pas dans la table <code className="font-mono">tenants</code> → violation de clé étrangère.</li>
                  <li>RLS bloque l'écriture (vérifiez que l'utilisateur est authentifié).</li>
                </ul>
              </div>
            </div>
          )}

          {/* Report downloads — opt-in via buttons (no auto-download) */}
          {reports && (reports.json || reports.excel) && (
            <div className="rounded-md border border-border p-3">
              <p className="text-xs font-medium text-foreground mb-2 flex items-center gap-1.5">
                <Download className="h-3.5 w-3.5" /> Rapports disponibles
              </p>
              <p className="text-[10px] text-muted-foreground mb-2">
                Cliquez sur un bouton pour télécharger le rapport. Les fichiers ne sont plus générés automatiquement.
              </p>
              <div className="grid grid-cols-2 gap-2">
                {reports.json && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => downloadReport(reports.json!, "application/json")}
                  >
                    <FileJson className="h-3.5 w-3.5" /> JSON
                  </Button>
                )}
                {reports.excel && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() =>
                      downloadReport(
                        reports.excel!,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                      )
                    }
                  >
                    <FileText className="h-3.5 w-3.5" /> Excel
                  </Button>
                )}
              </div>
              <p className="text-[10px] text-muted-foreground mt-2">
                Le rapport Excel contient 3 feuilles : Résumé, Lignes rejetées, Avertissements.
              </p>
            </div>
          )}

          {/* Audit log entry confirmation */}
          <div className="rounded-md bg-muted/30 p-3 text-xs text-muted-foreground">
            <p className="font-medium text-foreground mb-1">Audit log :</p>
            <p>
              Deux entrées ont été écrites dans le journal d'audit :
              <span className="font-mono text-foreground"> import.run_started</span> et
              <span className="font-mono text-foreground"> import.run_completed</span>
              (run ID : <span className="font-mono text-foreground">{commitCtx.runId}</span>).
              Consultez Paramètres → Audit pour les consulter.
            </p>
          </div>

          {commitCtx.errors.length > 0 && (
            <div className="rounded-md border border-status-warning/30 bg-status-warning/5 p-3 flex items-start gap-2">
              <AlertTriangle className="h-4 w-4 text-status-warning mt-0.5 shrink-0" />
              <p className="text-xs text-muted-foreground">
                Note: {commitCtx.errors.length} ligne(s) avec erreurs ont été ignorées (rollback atomique par feuille).
              </p>
            </div>
          )}
        </div>
      )}
    </UnifiedModal>
  );
}
