/**
 * Database type definitions for the Supabase adapter.
 *
 * These types mirror the SQL schema in `supabase/migrations/`. They are
 * deliberately hand-written (not generated by `supabase gen types`) so
 * the desktop app can be developed independently of a live Supabase project.
 * When the project is provisioned, run `supabase gen types --lang=ts` and
 * replace this file with the generated output for full type safety.
 */

// ============================================================================
// Multi-tenant + RBAC
// ============================================================================

export interface TenantRow {
  id: string;
  slug: string;
  name: string;
  legal_name: string | null;
  tax_id: string | null;
  address: string | null;
  city: string | null;
  postal_code: string | null;
  country: string;
  phone: string | null;
  email: string | null;
  website: string | null;
  logo_path: string | null;
  default_locale: string;
  default_currency: string;
  timezone: string;
  is_active: boolean;
  settings: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface UserProfileRow {
  id: string;
  auth_user_id: string;
  tenant_id: string | null;
  email: string;
  display_name: string | null;
  avatar_url: string | null;
  phone: string | null;
  locale: string;
  status: "pending" | "active" | "suspended" | "deleted";
  approval_request_id: string | null;
  last_login_at: string | null;
  last_login_ip: string | null;
  last_user_agent: string | null;
  password_changed_at: string | null;
  failed_login_count: number;
  locked_until: string | null;
  created_at: string;
  updated_at: string;
}

export interface AccountApprovalRequestRow {
  id: string;
  tenant_id: string | null;
  auth_user_id: string;
  email: string;
  requested_role: "parent" | "student" | "staff";
  requested_at: string;
  activation_code: string | null;
  national_id: string | null;
  phone: string | null;
  full_name: string | null;
  notes_from_user: string | null;
  target_parent_id: string | null;
  target_student_id: string | null;
  status: "pending" | "approved" | "rejected" | "expired";
  reviewed_by: string | null;
  reviewed_at: string | null;
  decision_note: string | null;
  created_at: string;
  updated_at: string;
  expires_at: string;
}

export interface RoleRow {
  id: string;
  code: string;
  label_fr: string;
  label_ar: string | null;
  label_en: string | null;
  description: string | null;
  staff_category: "administration" | "teaching" | "support" | "medical" | null;
  is_staff_role: boolean;
  is_web_role: boolean;
  sort_order: number;
}

export interface PermissionRow {
  id: string;
  code: string;
  label_fr: string;
  label_ar: string | null;
  label_en: string | null;
  domain: string;
  description: string | null;
  sort_order: number;
}

// ============================================================================
// Academic
// ============================================================================

export interface AcademicYearRow {
  id: string;
  tenant_id: string;
  /** Short code ("2025-2026") — added by migration 0029. */
  code: string | null;
  label: string;
  start_date: string;
  end_date: string;
  term_structure: "semester" | "trimester" | "quarter";
  is_current: boolean;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

export interface AcademicLevelRow {
  id: string;
  tenant_id: string;
  cycle: "prescolaire" | "primaire" | "cem" | "lycee";
  year_label: string;
  /** French label ("1ère Année Primaire") — added by migration 0029. */
  label_fr: string | null;
  /** Arabic label — added by migration 0029. */
  label_ar: string | null;
  year_number: number;
  grade_code: string;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface ClassRow {
  id: string;
  tenant_id: string;
  academic_year_id: string;
  academic_level_id: string;
  section: string;
  code: string;
  name: string | null;
  capacity: number;
  homeroom_teacher_id: string | null;
  /** Denormalized homeroom teacher name — added by migration 0029. */
  homeroom_teacher_name: string | null;
  /** Grade-level code ("3ap") — added by migration 0029. */
  grade_code: string | null;
  room: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface SubjectRow {
  id: string;
  tenant_id: string;
  code: string;
  name_fr: string;
  name_ar: string | null;
  name_en: string | null;
  domain: "scolarite" | "club" | "therapy" | "auxiliary";
  /** Academic cycle — added by migration 0029. */
  cycle: "prescolaire" | "primaire" | "cem" | "lycee" | null;
  default_coefficient: number;
  /** Passing grade (default 10) — added by migration 0029. */
  passing_grade: number;
  /** Extracurricular flag — added by migration 0029. */
  is_extracurricular: boolean;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// CRM
// ============================================================================

export interface ParentRow {
  id: string;
  tenant_id: string;
  parent_code: string;
  first_name: string;
  last_name: string;
  /**
   * COMPLETE display name as imported (e.g. "BENALI Mohamed").
   * When non-null, the UI MUST show this verbatim — never fall back to
   * first_name/last_name. Fixes the "Tuteur BENALI" prefix bug.
   *
   * Added by migration 0027_shared_unification.sql.
   */
  display_name: string | null;
  primary_phone: string;
  secondary_phone: string | null;
  email: string | null;
  national_id: string | null;
  occupation: string | null;
  address: string | null;
  city: string | null;
  postal_code: string | null;
  relationship: "father" | "mother" | "guardian" | "other" | null;
  notes: string | null;
  is_active: boolean;
  is_financially_restricted: boolean;
  auth_user_id: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface StudentRow {
  id: string;
  tenant_id: string;
  parent_id: string;
  student_code: string;
  first_name: string;
  middle_name: string | null;
  last_name: string;
  /**
   * COMPLETE display name as imported. When non-null, UI shows this verbatim.
   * Added by migration 0027_shared_unification.sql.
   */
  display_name: string | null;
  date_of_birth: string;
  gender: "male" | "female" | "other" | null;
  grade_level_id: string | null;
  class_id: string | null;
  enrollment_date: string;
  enrollment_status: "inquiry" | "quoted" | "enrolled" | "active" | "withdrawn" | "graduated";
  medical_notes: string | null;
  is_active: boolean;
  auth_user_id: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

// ============================================================================
// Financial
// ============================================================================

export interface PaymentRow {
  id: string;
  tenant_id: string;
  payment_number: string;
  /**
   * Alias for `payment_number` — kept in sync by trigger `sync_payments_receipt_number`.
   * Used by the unified financial RPCs and the desktop domain model.
   * Added by migration 0027_shared_unification.sql.
   */
  receipt_number: string | null;
  parent_id: string;
  student_id: string | null;
  invoice_id: string | null;
  installment_id: string | null;
  amount: number;
  method: "cash" | "check" | "transfer";
  /**
   * Billing category — drives which ledger account the payment lands on.
   * Added by migration 0027_shared_unification.sql.
   */
  category: "tuition" | "transport" | "canteen" | "uniform" | "books" |
            "extracurricular" | "therapy_psychology" | "therapy_speech" |
            "second_apron" | "parent_credit" | "other";
  check_number: string | null;
  check_bank_name: string | null;
  check_issue_date: string | null;
  check_clearance_date: string | null;
  transfer_reference: string | null;
  transfer_source_bank: string | null;
  proof_path: string | null;
  status: "paid" | "pending" | "unpaid" | "refunded" | "cancelled" | "partial" | "overdue" | "pending_clearance";
  collected_at: string;
  collected_by: string | null;
  notes: string | null;
  reversal_of_payment_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface InstallmentRow {
  id: string;
  tenant_id: string;
  parent_id: string;
  student_id: string;
  /** Optional FK to service_enrollments. NULL for bulk-imported tranches (migration 0032). */
  service_enrollment_id: string | null;
  invoice_id: string | null;
  tranche_number: 1 | 2 | 3;
  /** Human-readable tranche label (migration 0032). */
  label?: string | null;
  /** Billing category — denormalized from service_enrollments for bulk-imported rows (migration 0032). */
  category?: string | null;
  amount_due: number;
  amount_paid: number;
  /**
   * Uncleared non-cash funds (pending check/transfer) sitting on this tranche.
   * Invariant 4: a tranche is "paid" only when amount_paid >= amount_due;
   * amount_pending is excluded from satisfaction until the payment clears.
   */
  amount_pending: number;
  due_date: string;
  paid_date: string | null;
  status: "unpaid" | "partial" | "paid" | "overdue" | "pending_clearance";
  academic_cycle: "prescolaire" | "primaire" | "cem" | "lycee" | null;
  payment_plan: "full_annual" | "tranches";
  is_custom_schedule: boolean;
  custom_schedule_note: string | null;
  /** Provenance — "bulk_import" / "manual_entry" / null (migration 0032). */
  source_type?: string | null;
  /** Stable id within the source (migration 0032). */
  source_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface LedgerEntryRow {
  id: string;
  tenant_id: string;
  entry_number: string;
  parent_id: string;
  student_id: string | null;
  service_enrollment_id: string | null;
  payment_id: string | null;
  adjustment_id: string | null;
  reverses_entry_id: string | null;
  account_id: string;
  entry_type: "charge" | "payment" | "adjustment" | "refund" | "reversal" | "transfer";
  amount: number;
  category: string;
  description: string | null;
  entry_date: string;
  created_at: string;
  // ── Unified columns (added by migration 0027_shared_unification.sql) ──
  // These mirror the desktop domain `LedgerEntry` shape and the 0026 RPCs.
  source_type: string | null;
  source_id: string | null;
  method: "cash" | "check" | "transfer" | null;
  receipt_number: string | null;
  payment_status: string | null;
  reverses_id: string | null;
  actor_id: string | null;
  actor_name: string | null;
  at: string | null;
  metadata: Record<string, unknown> | null;
}

// ============================================================================
// Expenses + HR + Workforce + Operations + Workflow + Audit
// ============================================================================

export interface ExpenseTicketRow {
  id: string;
  tenant_id: string;
  ticket_number: string;
  title: string;
  description: string;
  category_id: string;
  requested_amount: number;
  final_spent_amount: number | null;
  justification: string;
  urgency: "low" | "medium" | "high" | "critical";
  status: "draft" | "pending_approval" | "approved_funds_released" | "rejected" | "disbursed" | "settled_and_closed";
  submitted_by: string;
  submitted_at: string;
  approved_by: string | null;
  approved_at: string | null;
  approval_note: string | null;
  rejected_reason: string | null;
  disbursed_at: string | null;
  settled_by: string | null;
  settled_at: string | null;
  receipt_path: string | null;
  receipt_uploaded_at: string | null;
  receipt_uploaded_by: string | null;
  anomaly_score: number | null;
  anomaly_flags_json: unknown[];
  created_at: string;
  updated_at: string;
}

export interface PersonnelRow {
  id: string;
  tenant_id: string;
  personnel_code: string;
  user_id: string | null;
  first_name: string;
  last_name: string;
  middle_name: string | null;
  date_of_birth: string | null;
  gender: "male" | "female" | "other" | null;
  national_id: string | null;
  staff_category: "administration" | "teaching" | "support" | "medical";
  role_id: string | null;
  department_id: string | null;
  supervisor_id: string | null;
  position: string | null;
  hire_date: string;
  end_date: string | null;
  is_active: boolean;
  base_salary: number | null;
  payment_method: "cash" | "bank_transfer" | "check" | null;
  bank_account: string | null;
  bonuses_json: unknown[];
  primary_phone: string | null;
  secondary_phone: string | null;
  email: string | null;
  address: string | null;
  emergency_contact: Record<string, unknown>;
  documents_json: unknown[];
  notes: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface AuditLogRow {
  id: string;
  tenant_id: string;
  action: string;
  entity_type: string;
  entity_id: string | null;
  actor_id: string | null;
  actor_name: string | null;
  actor_role: string | null;
  session_id: string | null;
  before_json: Record<string, unknown> | null;
  after_json: Record<string, unknown> | null;
  /** Compat alias used by the 0026 atomic RPCs. Computed from before/after. */
  diff: Record<string, unknown> | null;
  note: string | null;
  ip_address: string | null;
  user_agent: string | null;
  request_id: string | null;
  supersedes_id: string | null;
  occurred_at: string;
  created_at: string;
}

// ============================================================================
// Shared sync + device-token tables (migration 0027_shared_unification.sql)
// ============================================================================

export interface SyncQueueRow {
  id: string;
  tenant_id: string;
  entity: string;
  operation: "insert" | "update" | "delete";
  actor_id: string | null;
  payload: Record<string, unknown>;
  source_file: string | null;
  import_run_id: string | null;
  status: "pending" | "synced" | "failed" | "skipped_mock";
  attempts: number;
  last_error: string | null;
  queued_at: string;
  last_attempt_at: string | null;
  pushed_at: string | null;
  created_at: string;
}

export interface DeviceTokenRow {
  id: string;
  tenant_id: string;
  user_id: string;
  token: string;
  platform: "android" | "ios" | "web";
  app_version: string | null;
  is_active: boolean;
  last_seen_at: string;
  created_at: string;
  updated_at: string;
}

export interface NotificationRow {
  id: string;
  tenant_id: string;
  kind: "alert" | "info" | "warning" | "success" | "error" | "system";
  title: string;
  body: string | null;
  priority: "low" | "medium" | "high" | "urgent";
  source: "system" | "manual" | "workflow" | "schedule" | "audit";
  source_label: string | null;
  target_user_id: string | null;
  target_role: string | null;
  is_read: boolean;
  read_at: string | null;
  dismissed_at: string | null;
  triggered_at: string;
  expires_at: string | null;
  link_entity_type: string | null;
  link_entity_id: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// Departments (migration 0010_workforce.sql)
// ============================================================================

export interface DepartmentRow {
  id: string;
  tenant_id: string;
  code: string;
  name_fr: string;
  label_ar: string | null;
  color_hex: string | null;
  head_personnel_id: string | null;
  description: string | null;
  sort_order: number;
  is_active: boolean;
  is_archived: boolean;
  created_at: string;
  updated_at: string;
}

// ============================================================================
// Convenience type: the Database shape expected by Supabase's typed client
// ============================================================================

export interface Database {
  public: {
    Tables: {
      tenants: { Row: TenantRow; Insert: Partial<TenantRow>; Update: Partial<TenantRow> };
      user_profiles: { Row: UserProfileRow; Insert: Partial<UserProfileRow>; Update: Partial<UserProfileRow> };
      account_approval_requests: { Row: AccountApprovalRequestRow; Insert: Partial<AccountApprovalRequestRow>; Update: Partial<AccountApprovalRequestRow> };
      roles: { Row: RoleRow; Insert: Partial<RoleRow>; Update: Partial<RoleRow> };
      permissions: { Row: PermissionRow; Insert: Partial<PermissionRow>; Update: Partial<PermissionRow> };
      academic_years: { Row: AcademicYearRow; Insert: Partial<AcademicYearRow>; Update: Partial<AcademicYearRow> };
      academic_levels: { Row: AcademicLevelRow; Insert: Partial<AcademicLevelRow>; Update: Partial<AcademicLevelRow> };
      classes: { Row: ClassRow; Insert: Partial<ClassRow>; Update: Partial<ClassRow> };
      subjects: { Row: SubjectRow; Insert: Partial<SubjectRow>; Update: Partial<SubjectRow> };
      departments: { Row: DepartmentRow; Insert: Partial<DepartmentRow>; Update: Partial<DepartmentRow> };
      parents: { Row: ParentRow; Insert: Partial<ParentRow>; Update: Partial<ParentRow> };
      students: { Row: StudentRow; Insert: Partial<StudentRow>; Update: Partial<StudentRow> };
      payments: { Row: PaymentRow; Insert: Partial<PaymentRow>; Update: Partial<PaymentRow> };
      installments: { Row: InstallmentRow; Insert: Partial<InstallmentRow>; Update: Partial<InstallmentRow> };
      ledger_entries: { Row: LedgerEntryRow; Insert: Partial<LedgerEntryRow>; Update: Partial<LedgerEntryRow> };
      expense_tickets: { Row: ExpenseTicketRow; Insert: Partial<ExpenseTicketRow>; Update: Partial<ExpenseTicketRow> };
      personnel: { Row: PersonnelRow; Insert: Partial<PersonnelRow>; Update: Partial<PersonnelRow> };
      audit_logs: { Row: AuditLogRow; Insert: Partial<AuditLogRow>; Update: Partial<AuditLogRow> };
      notifications: { Row: NotificationRow; Insert: Partial<NotificationRow>; Update: Partial<NotificationRow> };
      sync_queue: { Row: SyncQueueRow; Insert: Partial<SyncQueueRow>; Update: Partial<SyncQueueRow> };
      device_tokens: { Row: DeviceTokenRow; Insert: Partial<DeviceTokenRow>; Update: Partial<DeviceTokenRow> };
    };
    Views: {
      vw_dashboard_kpis: { Row: Record<string, unknown> };
      vw_student_roster: { Row: Record<string, unknown> };
      vw_personnel_directory: { Row: Record<string, unknown> };
      vw_audit_log_with_actor: { Row: AuditLogRow & { actor_email: string | null; actor_display_name: string | null } };
    };
    Functions: {
      current_tenant_id: { Args: Record<string, never>; Returns: string };
      current_user_profile_id: { Args: Record<string, never>; Returns: string };
      current_user_roles: { Args: Record<string, never>; Returns: string[] };
      current_user_permissions: { Args: Record<string, never>; Returns: string[] };
      has_permission: { Args: { p_code: string }; Returns: boolean };
      has_role: { Args: { r_code: string }; Returns: boolean };
      write_audit_log: {
        Args: {
          p_tenant_id: string;
          p_action: string;
          p_entity_type: string;
          p_entity_id?: string | null;
          p_actor_id?: string | null;
          p_actor_name?: string | null;
          p_actor_role?: string | null;
          p_session_id?: string | null;
          p_before_json?: unknown;
          p_after_json?: unknown;
          p_note?: string | null;
          p_ip_address?: string | null;
          p_user_agent?: string | null;
          p_request_id?: string | null;
        };
        Returns: string;
      };
      compute_account_balance: { Args: { p_account_id: string }; Returns: number };
      compute_parent_outstanding: { Args: { p_parent_id: string }; Returns: number };
      compute_overdue_amount: { Args: { p_parent_id: string; p_as_of?: string }; Returns: number };
      generate_activation_code: { Args: { p_tenant_id: string }; Returns: string };
      bind_activation_code: { Args: { p_tenant_id: string; p_code: string; p_auth_user_id: string }; Returns: unknown };
      approve_account_request: {
        Args: {
          p_request_id: string;
          p_reviewer_profile_id: string;
          p_target_parent_id?: string | null;
          p_target_student_id?: string | null;
          p_decision_note?: string | null;
        };
        Returns: string;
      };
      reject_account_request: {
        Args: { p_request_id: string; p_reviewer_profile_id: string; p_decision_note: string };
        Returns: void;
      };
      batch_register_family: {
        Args: {
          p_tenant_id: string;
          p_parent: unknown;
          p_students: unknown;
          p_actor_profile_id: string;
          p_activation_code?: string | null;
        };
        Returns: unknown;
      };
      collect_payment: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      refund_payment: {
        Args: { p_tenant_id: string; p_payment_id: string; p_actor_profile_id: string; p_reason: string };
        Returns: string;
      };
      /**
       * UNIFIED ARCHITECTURE: Atomic payment collection + waterfall allocation.
       *
       * Replaces the multi-step client-side flow (insert payment → insert
       * ledger entry → update installments) with a single RPC that wraps
       * everything in BEGIN ... COMMIT. If any step fails, the entire
       * transaction rolls back — no partial state is ever visible.
       *
       * Implementation: `supabase/migrations/0026_unified_financial.sql`.
       */
      collect_and_allocate_payment: {
        Args: {
          p_tenant_id: string;
          p_parent_id: string;
          p_student_id: string | null;
          p_amount: number;
          p_method: "cash" | "check" | "transfer";
          p_category: string;
          p_installment_id: string | null;
          p_proof_path: string | null;
          p_notes: string | null;
          p_actor_id: string;
          p_actor_name: string;
        };
        Returns: {
          payment_id: string;
          receipt_number: string;
          payment_status: string;
          total_allocated: number;
          unallocated_credit: number;
          allocations: unknown; // JSONB array of { installmentId, allocatedAmount, newAmountPaid, newStatus, fullySatisfied }
        };
      };
      /**
       * UNIFIED ARCHITECTURE: Atomic payment reversal + LIFO un-allocation.
       *
       * Replaces the multi-step client-side refund flow (mark refunded →
       * append reversal entry → revert installment amountPaid) with a
       * single RPC. Implements Invariant 5 (Reversal Balance).
       *
       * Implementation: `supabase/migrations/0026_unified_financial.sql`.
       */
      revert_payment_allocation: {
        Args: {
          p_tenant_id: string;
          p_payment_id: string;
          p_actor_id: string;
          p_actor_name: string;
          p_reason: string;
        };
        Returns: {
          payment_id: string;
          new_status: string;
          reversal_entry_id: string;
          reverts_count: number;
          total_reverted: number;
        };
      };
      run_overdue_scan: { Args: { p_tenant_id: string; p_as_of?: string }; Returns: unknown };
      expire_pending_approvals: { Args: Record<string, never>; Returns: number };
      refresh_all_materialized_views: { Args: Record<string, never>; Returns: void };
      // ── Shared unification RPCs (migration 0027) ──
      register_fcm_token: {
        Args: { p_user_id: string; p_token: string; p_platform?: string };
        Returns: string;
      };
      upsert_parent_from_import: {
        Args: {
          p_tenant_id: string;
          p_parent_code: string;
          p_first_name: string;
          p_last_name: string;
          p_display_name?: string | null;
          p_primary_phone?: string | null;
          p_secondary_phone?: string | null;
          p_email?: string | null;
          p_occupation?: string | null;
          p_address?: string | null;
          p_city?: string | null;
          p_relationship?: string | null;
          p_preferred_language?: string;
          p_is_active?: boolean;
          // Migration 0028 — transport destination + city tier (parity with
          // Android's pull_parents_for_sync read-back).
          p_transport_destination?: string | null;
          p_city_tier?: string | null;
          // Migration 0037 / vault §02.08 — deterministic activation code so
          // imported/registered parents can activate the Web Portal.
          p_activation_code?: string | null;
        };
        // Migration 0031 — output columns renamed to out_* (plpgsql
        // "column reference is ambiguous" fix).
        Returns: { out_parent_id: string; out_parent_code: string; out_was_inserted: boolean }[];
      };
      upsert_student_from_import: {
        Args: {
          p_tenant_id: string;
          p_student_code: string;
          p_parent_id: string;
          p_first_name: string;
          p_last_name: string;
          p_display_name?: string | null;
          p_middle_name?: string | null;
          p_date_of_birth?: string | null;
          p_gender?: string | null;
          p_grade_level_id?: string | null;
          p_class_id?: string | null;
          p_enrollment_date?: string | null;
          p_enrollment_status?: string;
          p_medical_notes?: string | null;
          p_is_active?: boolean;
        };
        Returns: { student_id: string; student_code: string; was_inserted: boolean }[];
      };
      upsert_payment_from_import: {
        Args: Record<string, unknown>;
        Returns: { payment_id: string; payment_number: string; was_inserted: boolean }[];
      };
      upsert_ledger_entry_from_import: {
        Args: Record<string, unknown>;
        Returns: { entry_id: string; was_inserted: boolean }[];
      };
      mark_sync_queue_processed: {
        Args: { p_id: string; p_status: string; p_error?: string | null };
        Returns: void;
      };
      pull_parents_for_sync: { Args: { p_tenant_id: string; p_since?: string; p_limit?: number }; Returns: unknown };
      pull_students_for_sync: { Args: { p_tenant_id: string; p_since?: string; p_limit?: number }; Returns: unknown };
      pull_payments_for_sync: { Args: { p_tenant_id: string; p_since?: string; p_limit?: number }; Returns: unknown };
      pull_ledger_entries_for_sync: { Args: { p_tenant_id: string; p_since?: string; p_limit?: number }; Returns: unknown };
      pull_device_tokens_for_sync: { Args: { p_tenant_id: string; p_since?: string; p_limit?: number }; Returns: unknown };
    };
  };
}
