/**
 * T-455 (PARITY-007, 127th session — the issue-#1 follow-up): the
 * cross-platform UI-SURFACE parity test — the DESKTOP leg.
 *
 * The owner's mandate (issue #1 §6/§11): the full data-flow comparison must
 * reach the UI-facing values, and the underlying values must actually match
 * — never merely be formatted similarly. This suite closes the triangle at
 * the DISPLAY layer:
 *
 *   Excel source data → canonical business engine (derivePooledTrancheWaves
 *   + the strip adapters) → corpus then-blocks → Desktop UI ≡ Android UI
 *
 * The proof legs:
 *   1. THE ENGINE LEG — the REAL desktop derivations (the same
 *      analytics_bridge adapters the desktop runner and the production
 *      Finance strip / Statistics wave cards consume) reproduce every
 *      ui_surfaces scenario's then-block EXACTLY (the corpus's expected
 *      values are BY CONSTRUCTION the desktop engine's output — generated by
 *      scripts/generate_executive_statistics_corpus.ts; this suite re-proves
 *      it against the committed corpus so a hand-edited then-block cannot
 *      slip through).
 *   2. THE EXCEL SOURCE-OF-TRUTH LEG — the scenario's given carries the
 *      REAL Excel 2025-2026 corpus family (t105_00267128 — OUAAMRI ARIS:
 *      23 850 000 DZD charged = paid, outstanding 0 — the values the
 *      t105 corpus pins from the reconciled Excel data). The strip totals
 *      must equal the source-of-truth sums over the scenario's own rows,
 *      and the Excel family's contribution must be intact inside them.
 *   3. THE RECONCILIATION-IDENTITY LEG — every pooled wave slot must hold
 *      the T-447 mandate identity
 *      `dueTotal + overCoverageTotal = paidTotal + pendingTotal + remainingTotal`
 *      ("Total Due = Paid + Pending + Remaining", exact per wave — the
 *      numbers the wave cards render, asserted NUMERICALLY, never via
 *      formatted strings).
 *   4. THE REGRESSION SENTINEL — the label-parsing wave derivation is
 *      retired: a row whose label says "Tranche 10" but whose canonical
 *      tranche_number says 1 must be IN wave 1 (the pre-T-454 Android feed
 *      silently dropped such rows; the corpus pins the class).
 *
 * The ANDROID leg of this triangle is the Android repo's
 * `CrossPlatformEquivalenceTest > every ui_surfaces scenario matches the
 * desktop-generated expectations` (the same corpus, the Kotlin engine), and
 * the RUNNER-level leg is `comparison/comparator.ts` (the desktop runner vs
 * the real Kotlin runner — 320/320 at T-455). A failure HERE means the
 * desktop would render a DIFFERENT wave-card / Finance-strip number than
 * the canonical engine output.
 */
import { describe, test, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import {
  deriveTrancheWavesFor,
  deriveTrancheStripTotalsFor,
  derivePooledTrancheWaves,
  deriveNonWaveSummary,
  emptyPooledWave,
} from "../../../financial-tests/equivalence/desktop/analytics_bridge";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface UiSurfacesScenario {
  id: string;
  description?: string;
  category?: string;
  when?: { type?: string; now?: string };
  given?: {
    installments?: Array<{
      id?: string;
      parentId: string;
      label?: string;
      category?: string;
      trancheNumber?: number;
      amountDue: number;
      amountPaid?: number;
      amountPending?: number;
      dueDate: string;
      status: string;
    }>;
  };
  then?: Record<string, unknown>;
}

function loadUiSurfacesScenarios(): UiSurfacesScenario[] {
  const scenariosDir = path.resolve(
    __dirname,
    "../../../financial-tests/equivalence/scenarios",
  );
  const out: UiSurfacesScenario[] = [];
  for (const file of fs.readdirSync(scenariosDir)) {
    if (!file.endsWith(".json")) continue;
    const scenario: UiSurfacesScenario = JSON.parse(
      fs.readFileSync(path.join(scenariosDir, file), "utf-8"),
    );
    if (scenario.category !== "executive_statistics") continue;
    if (scenario.when?.type !== "deriveUiSurfaces") continue;
    out.push(scenario);
  }
  return out;
}

const SCENARIOS = loadUiSurfacesScenarios();

describe("T-455: the cross-platform UI-surface parity — the desktop leg", () => {
  test("the corpus carries at least one ui_surfaces scenario", () => {
    expect(SCENARIOS.length).toBeGreaterThan(0);
    expect(SCENARIOS.map((s) => s.id)).toContain("executive_statistics_ui_surfaces");
  });

  for (const scenario of SCENARIOS) {
    describe(`scenario ${scenario.id}`, () => {
      const nowEpochMs = Date.parse(scenario.when?.now ?? "2026-10-01T00:00:00Z");
      const rows = (scenario.given?.installments ?? []).map((i) => ({
        parentId: i.parentId,
        label: i.label ?? "",
        category: i.category ?? "tuition",
        trancheNumber: i.trancheNumber ?? 1,
        // The corpus stores CENTIMES; the desktop domain is DZD.
        amountDue: i.amountDue / 100,
        amountPaid: (i.amountPaid ?? 0) / 100,
        amountPending: (i.amountPending ?? 0) / 100,
        dueDate: i.dueDate,
        status: i.status,
      }));
      const installments = rows.map((r, idx) => ({
        id: `t-${idx}`,
        parentId: r.parentId,
        studentId: null,
        category: r.category as never,
        label: r.label,
        trancheNumber: r.trancheNumber as 1 | 2 | 3,
        amountDue: r.amountDue,
        amountPaid: r.amountPaid,
        amountPending: r.amountPending,
        dueDate: r.dueDate,
        paidDate: null,
        status: r.status as never,
        academicCycle: undefined,
        paymentPlan: "tranches" as const,
        isCustomSchedule: false,
        customSchedule: false,
        customScheduleNote: null,
      }));

      const stripWaves = deriveTrancheWavesFor(rows, nowEpochMs);
      const stripTotals = deriveTrancheStripTotalsFor(rows, nowEpochMs);
      const pooled = derivePooledTrancheWaves(installments, nowEpochMs);
      const nonWave = deriveNonWaveSummary(installments, nowEpochMs);
      const slots = ([1, 2, 3] as const).map(
        (wave) => pooled.find((p) => p.wave === wave) ?? emptyPooledWave(wave),
      );

      const then = scenario.then as {
        financeStripWaves: Array<{
          index: number;
          due: number;
          paid: number;
          pending: number;
          remaining: number;
          pct: number;
          tuitionPct: number | null;
          isNextTarget: boolean;
          isOverdue: boolean;
        }>;
        financeStripTotals: { totalDue: number; totalPaid: number; totalRemaining: number; overdueCount: number };
        waveVelocityCards: {
          globalBadges: { globalPct: number; totalPending: number; totalRemaining: number };
          slots: Array<{
            wave: number;
            dueTotal: number;
            paidTotal: number;
            pendingTotal: number;
            remainingTotal: number;
            overCoverageTotal: number;
            collectedPct: number;
            isComplete: boolean;
            isOverdue: boolean;
            statusText: string;
            daysLate: number;
            perCategoryCount: number;
          }>;
        };
        nonWaveSummary: Array<{ kind: string; category: string; installmentCount: number; remainingTotal: number }>;
      };

      test("THE ENGINE LEG — the strip view model equals the desktop-generated then-block (the Finance strip's rendered values)", () => {
        expect(stripWaves).toHaveLength(then.financeStripWaves.length);
        then.financeStripWaves.forEach((expected, i) => {
          const actual = stripWaves[i];
          expect(actual.index).toBe(expected.index);
          expect(actual.due * 100).toBe(expected.due);
          expect(actual.paid * 100).toBe(expected.paid);
          expect(actual.pending * 100).toBe(expected.pending);
          expect(actual.remaining * 100).toBe(expected.remaining);
          expect(actual.pct).toBe(expected.pct);
          expect(actual.tuitionPct).toBe(expected.tuitionPct);
          expect(actual.isNextTarget).toBe(expected.isNextTarget);
          expect(actual.isOverdue).toBe(expected.isOverdue);
        });
      });

      test("THE ENGINE LEG — the strip totals equal the then-block (the 4-cell totals row)", () => {
        expect(stripTotals.totalDue * 100).toBe(then.financeStripTotals.totalDue);
        expect(stripTotals.totalPaid * 100).toBe(then.financeStripTotals.totalPaid);
        expect(stripTotals.totalRemaining * 100).toBe(then.financeStripTotals.totalRemaining);
        expect(stripTotals.overdueCount).toBe(then.financeStripTotals.overdueCount);
      });

      test("THE ENGINE LEG — the wave-velocity card slots equal the then-block (the wave hero's rendered values, incl. the status + days-late)", () => {
        expect(slots).toHaveLength(then.waveVelocityCards.slots.length);
        then.waveVelocityCards.slots.forEach((expected, i) => {
          const w = slots[i];
          expect(w.wave).toBe(expected.wave);
          expect(w.dueTotal * 100).toBe(expected.dueTotal);
          expect(w.paidTotal * 100).toBe(expected.paidTotal);
          expect(w.pendingTotal * 100).toBe(expected.pendingTotal);
          expect(w.remainingTotal * 100).toBe(expected.remainingTotal);
          expect(w.overCoverageTotal * 100).toBe(expected.overCoverageTotal);
          expect(w.collectedPct).toBe(expected.collectedPct);
          expect(w.installmentCount > 0 && w.remainingTotal === 0).toBe(expected.isComplete);
          expect(w.anyUnsettledOverdue).toBe(expected.isOverdue);
          const statusText =
            expected.isComplete ? "Clôturée" : expected.isOverdue ? "En retard" : "En cours";
          expect(statusText).toBe(expected.statusText);
          const daysLate =
            w.dueDateMin === null
              ? 0
              : Math.floor((nowEpochMs - w.dueDateMin) / 86_400_000);
          expect(daysLate).toBe(expected.daysLate);
          expect(w.perCategory.length).toBe(expected.perCategoryCount);
        });
        const totalPending = pooled.reduce((s, w) => s + w.pendingTotal, 0);
        const totalRemaining = pooled.reduce((s, w) => s + w.remainingTotal, 0);
        const totalDue = pooled.reduce((s, w) => s + w.dueTotal, 0);
        const totalPaid = pooled.reduce((s, w) => s + w.paidTotal, 0);
        const globalPct = totalDue > 0 ? Math.round((totalPaid / totalDue) * 100) : 0;
        expect(globalPct).toBe(then.waveVelocityCards.globalBadges.globalPct);
        expect(totalPending * 100).toBe(then.waveVelocityCards.globalBadges.totalPending);
        expect(totalRemaining * 100).toBe(then.waveVelocityCards.globalBadges.totalRemaining);
      });

      test("THE ENGINE LEG — the non-wave « Hors Tranches » groups equal the then-block", () => {
        expect(nonWave).toHaveLength(then.nonWaveSummary.length);
        then.nonWaveSummary.forEach((expected, i) => {
          expect(nonWave[i].kind).toBe(expected.kind);
          expect(nonWave[i].category).toBe(expected.category);
          expect(nonWave[i].installmentCount).toBe(expected.installmentCount);
          expect(nonWave[i].remainingTotal * 100).toBe(expected.remainingTotal);
        });
      });

      test("THE EXCEL LEG — the strip totals equal the source-of-truth sums over the scenario's own rows", () => {
        const rawRows = scenario.given?.installments ?? [];
        const excelDue = rawRows.reduce((s, i) => s + i.amountDue, 0);
        const excelPaid = rawRows.reduce((s, i) => s + (i.amountPaid ?? 0), 0);
        const excelPending = rawRows.reduce((s, i) => s + (i.amountPending ?? 0), 0);
        expect(then.financeStripTotals.totalDue).toBe(excelDue);
        expect(then.financeStripTotals.totalPaid).toBe(excelPaid);
        expect(then.financeStripTotals.totalRemaining).toBe(
          Math.max(0, excelDue - excelPaid - excelPending),
        );
      });

      test("THE EXCEL LEG — the t105 Excel family's totals are intact inside the strip totals (23 850 000 DZD charged = paid)", () => {
        // The OUAAMRI ARIS rows (the REAL Excel 2025-2026 corpus family —
        // t105_00267128): 8 480 000 + 6 360 000 + 9 010 000 centimes charged,
        // all paid, outstanding 0.
        const excelFamily = (scenario.given?.installments ?? []).filter((i) =>
          i.parentId === "par-00267128",
        );
        expect(excelFamily.length).toBe(3);
        const familyDue = excelFamily.reduce((s, i) => s + i.amountDue, 0);
        const familyPaid = excelFamily.reduce((s, i) => s + (i.amountPaid ?? 0), 0);
        expect(familyDue).toBe(23_850_000);
        expect(familyPaid).toBe(23_850_000);
        // The family's contribution is INSIDE the strip totals (the whole
        // selection, never dropped).
        expect(then.financeStripTotals.totalDue).toBeGreaterThanOrEqual(familyDue);
        expect(then.financeStripTotals.totalPaid).toBeGreaterThanOrEqual(familyPaid);
      });

      test("THE IDENTITY LEG — every wave slot holds the T-447 reconciliation identity (Total Due = Paid + Pending + Remaining, + over-coverage when funds exceed the due)", () => {
        slots.forEach((w) => {
          expect(w.paidTotal + w.pendingTotal + w.remainingTotal).toBe(
            w.dueTotal + w.overCoverageTotal,
          );
        });
      });

      test("THE REGRESSION SENTINEL — the label is IRRELEVANT: the 'Tranche 10'-labeled row at column 1 is IN wave 1 (the retired label-regex feed dropped it)", () => {
        const rawRows = scenario.given?.installments ?? [];
        const trap = rawRows.find((i) => i.label === "Tranche 10");
        if (trap) {
          expect(trap.trancheNumber).toBe(1);
          // Its amounts are inside wave 1's pool (never silently dropped).
          const wave1 = pooled.find((w) => w.wave === 1);
          expect(wave1).toBeDefined();
          expect(wave1!.dueTotal * 100).toBeGreaterThanOrEqual(trap.amountDue);
        }
      });
    });
  }
});
