-- T-326 verification — the four reconstructed migrations (0088/0091/0092/0093)
-- are live-equivalent and idempotent.
-- NOTE: this script is executed with the four migration files INLINED by the
-- caller (scripts/apply-style harness; the Management API SQL endpoint has no
-- \ir support). The canonical payload lives in the session transcript and the
-- check set below is the reusable part:
--   A. 0091 policy exists (student_academic_histories_parent_select)
--   B. 0093 policy exists (attendance_parent_update_justification)
--   C. 0092 bucket exists (attendance-justifications, 10MB, private)
--   D. 0092 storage policies = 4
--   E. 0088 validate_workflow_dag accepts has_medical_justification
--   F. registrations 0088/0091/0092/0093 present
-- RESULT (2026-09-13, live, rollback-wrapped): 6/6 ok=true.
